*********************************
*				*
*    Problem 4 - CSL Project    *
*				*
*********************************
* REGISTER USES:
* R11 = RETURN ADDRESS
PROG4		START		0
		STM		14,12,12(13)
		BALR		12,0
		USING		*,12
		XR		1,1
		READCARD	FIRST,EOF
		LA		1,1(0,1)		INCREMENT R1
		READCARD	SECOND,EOF
		LA		1,1(0,1)		INCREMENT R1
		READCARD	OPERATOR,EOF
		BAL		11,SIZE
		CLC		OPERATOR(1),=C'+'	COMPARE LEN 1
		BE		ADDITION
		CLC		OPERATOR(1),=C'-'	COMPARE LEN 1
		BE		SUBTRACTION
		CLC		OPERATOR(1),=C'/'	COMPARE LEN 1
		BE		DIVISION
		CLC		OPERATOR(1),=C'*'	COMPARE LEN 1
		BE		MULTIPLICATION
CONTINUE	
* RETURN TO OS
EOF		LM 		14,12,12(13)
		BR		14

* CALCULATE SIZE OF INPUTS
SIZE		XR		10,10			SIZE = 0
SIZELOP1	CLC		FIRST(1,10),=C' '
		BE		ENDSIZE1
		LA		10,1(0,10)		INC SIZE
		B		SIZELOP1
ENDSIZE1	ST		10,FIRSTSIZE
		XR		10,10
SIZELOP2	CLC		SECOND(1,10),=C' '
		BE		ENDSIZE2
		LA		10,1(0,10)
		B		SIZELOP2
ENDSIZE2	ST		10,SECONDSIZE
		BR		11
* ADDITION
ADDITION	L		10,FIRSTSIZE

* VARIABLES
FIRSTSIZE	DC		CL80' '
SECOND		DC		CL80' '
FIRSTSIZE	DC		F'0'
SECONDSIZE	DC		F'0'
RESULT		DC		CL18' '
OPERATOR	DC		CL80' '
		END		PROG4
