*********************************
*				*
*    Problem 4 - CSL Project    *
*				*
*********************************
* REGISTER USES:
* R11 = RETURN ADDRESS
PROG4		START		0
		STM		14,12,12(13)
		BALR		12,0
		USING		*,12
		XR		1,1
		READCARD	FIRST,EOF
		LA		1,1(0,1)		INCREMENT R1
		READCARD	SECOND,EOF
		LA		1,1(0,1)		INCREMENT R1
		READCARD	OPERATOR,EOF
		BAL		11,SIZE
		CLC		OPERATOR(1),=C'+'	COMPARE LEN 1
		BE		ADDITION
		CLC		OPERATOR(1),=C'-'	COMPARE LEN 1
		BE		SUBTRACTION
CONTINUE	PRINTLIN	RESULT,80
* RETURN TO OS
EOF		LM 		14,12,12(13)
		BR		14
**********************
*      ADDITION      *
**********************
ADDITION	L		1,FIRSTSIZE	FIRST INDEX
		L		2,SECONDSIZE	SECOND INDEX
		LA		3,80		RESULT INDEX
		XR		6,6		CARRY
ADDLOOP		S		1,=F'1'
		S		2,=F'1'
		S		3,=F'1'
		C		1,=F'0'			A DIGIT FROM FIRST NUMBER
		BL		FZERO
		L		4,FIRST(1)
		SRL		4,24
		B		FCONT
FZERO		L		4,=C'0'
FCONT		C		2,=F'0'			A DIGIT FROM SECOND NUMBER
		BL		SZERO
		L		5,SECOND(2)
		SRL		5,24
		B		SCONT
SZERO		L		5,=C'0'
SCONT		S		4,=C'0'
		S		4,=C'0'
		AR		4,5		ADD DIGITS
		AR		4,6		ADD CARRY
		XR		6,6		CARRY = 0
		C		4,=F'10'
		BL		NOCARRY
		S		4,=F'10'
		LA		6,1		CARRY = 1
NOCARRY		C		4,=F'0'
		BE		CHECKEND
NOTEND		A		4,=C'0'
		ST		4,TEMP
		MVC		RESULT(1,3),TEMP
		B		ADDLOOP
CHECKEND	C		1,=F'0'
		BNL		NOTEND
		C		2,=F'0'
		BNL		NOTEND
		B		CONTINUE
**********************
*     SUBTRACTION    *
**********************
SUBTRACTION	L		1,FIRSTSIZE	FIRST INDEX
		L		2,SECONDSIZE	SECOND INDEX
		LA		3,80		RESULT INDEX
		XR		6,6		BORROW
SUBLOOP		S		1,=F'1'
		S		2,=F'1'
		S		3,=F'1'
		C		1,=F'0'		A DIGIT FROM FIRST NUMBER
		BL		CONTINUE
		L		4,FIRST(1)
		SRL		4,24
		C		2,=F'0'		A DIGIT FROM SECOND NUMBER
		BL		SZEROS
		L		5,SECOND(2)
		SRL		5,24
		B		SCONTS
SZEROS		L		5,=C'0'
SCONTS		S		4,=C'0'
		S		4,=C'0'
		SR		4,5		SUB DIGITS
		SR		4,6		SUB BORROW
		XR		6,6		BORROW = 0
		C		4,=F'0'
		BNL		NOBORROW
		A		4,=F'10'
		LA		6,1		BORROW = 1
NOBORROW	A		4,=C'0'
		ST		4,TEMP
		MVC		RESULT(1,3),TEMP
		B		SUBLOOP
* CALCULATE SIZE OF INPUTS
SIZE		XR		10,10			SIZE = 0
SIZELOP1	CLC		FIRST(1,10),=C' '
		BE		ENDSIZE1
		LA		10,1(0,10)		INC SIZE
		B		SIZELOP1
ENDSIZE1	ST		10,FIRSTSIZE
		XR		10,10
SIZELOP2	CLC		SECOND(1,10),=C' '
		BE		ENDSIZE2
		LA		10,1(0,10)
		B		SIZELOP2
ENDSIZE2	ST		10,SECONDSIZE
		BR		11
* VARIABLES
FIRST		DC		CL80' '
SECOND		DC		CL80' '
RESULT		DC		CL80' '
OPERATOR	DC		CL80' '
FIRSTSIZE	DC		F'0'
SECONDSIZE	DC		F'0'
TEMP		DC		CL10' '
		END		PROG4